#pragma once

/**
 * @file gpu_scene.hpp
 * @brief GPU-side scene representation for GPU-Driven Rendering
 *
 * This module manages GPU buffers containing all scene objects, their transforms,
 * bounding volumes, and draw commands. It enables single-dispatch culling and
 * indirect drawing for efficient rendering of large scenes.
 *
 * Architecture:
 * - GPUObjectData: Per-object transform and metadata (uploaded every frame)
 * - GPUMeshInfo: Static mesh geometry info (index count, offsets)
 * - GPUDrawCommand: Indirect draw arguments (generated by cull shader)
 */

#include "engine/core/types.hpp"
#include "engine/rhi/rhi_device.hpp"
#include "engine/rhi/rhi_resources.hpp"

#include <memory>
#include <vector>

#include <glm/glm.hpp>


namespace hz {

// Forward declarations
class Mesh;

// ============================================================================
// GPU Data Structures (must match shader layout)
// ============================================================================

/**
 * @brief Per-object data uploaded to GPU each frame
 *
 * Layout: std430 compatible (16-byte aligned)
 */
struct GPUObjectData {
    glm::mat4 model;                   // 64 bytes
    glm::mat4 inverse_transpose_model; // 64 bytes (for normal transformation)
    glm::vec4 bounding_sphere;         // 16 bytes (xyz=center in world space, w=radius)
    u32 mesh_index;                    // 4 bytes - index into GPUMeshInfo array
    u32 material_index;                // 4 bytes - index into material descriptor array
    u32 flags;                         // 4 bytes - visibility flags, shadow caster, etc.
    u32 _padding;                      // 4 bytes - alignment padding
    // Total: 160 bytes
};

/**
 * @brief Object flags for GPU culling and rendering
 */
enum class GPUObjectFlags : u32 {
    None = 0,
    Visible = 1 << 0,       // Object is potentially visible (not culled by CPU)
    CastShadow = 1 << 1,    // Object casts shadows
    ReceiveShadow = 1 << 2, // Object receives shadows
    Static = 1 << 3,        // Object doesn't move (for occlusion culling)
    All = 0xFFFFFFFF
};

/**
 * @brief Static mesh geometry information
 *
 * This is uploaded once when meshes are registered, not every frame.
 * Used by the cull shader to generate draw commands.
 */
struct GPUMeshInfo {
    u32 index_count;   // Number of indices
    u32 first_index;   // Offset into global index buffer
    i32 vertex_offset; // Offset into global vertex buffer
    u32 _padding;      // Alignment
};

/**
 * @brief Indirect draw command (matches VkDrawIndexedIndirectCommand)
 *
 * Generated by the GPU cull shader for visible objects.
 */
struct GPUDrawCommand {
    u32 index_count;
    u32 instance_count;
    u32 first_index;
    i32 vertex_offset;
    u32 first_instance; // Used to pass object_id to vertex shader
};

static_assert(sizeof(GPUDrawCommand) == 20, "GPUDrawCommand must be 20 bytes");

// ============================================================================
// GPU Scene Manager
// ============================================================================

/**
 * @brief Configuration for GPUScene
 */
struct GPUSceneConfig {
    u32 max_objects{16384};               // Maximum objects in scene
    u32 max_meshes{1024};                 // Maximum unique meshes
    u32 max_vertices{1 << 20};            // 1M vertices in mega-buffer
    u32 max_indices{1 << 21};             // 2M indices in mega-buffer
    bool enable_occlusion_culling{false}; // Hi-Z occlusion culling (future)
};

/**
 * @brief Manages GPU-side scene data for indirect rendering
 *
 * Usage:
 * 1. Call register_mesh() for each unique mesh at load time
 * 2. Call begin_frame() at start of frame
 * 3. Call add_object() for each renderable object
 * 4. Call end_frame() to upload data to GPU
 * 5. Use get_object_buffer(), get_mesh_info_buffer() for compute shader
 * 6. Use get_draw_command_buffer(), get_draw_count_buffer() for indirect draw
 */
class GPUScene {
public:
    explicit GPUScene(rhi::Device& device, const GPUSceneConfig& config = {});
    ~GPUScene();

    HZ_NON_COPYABLE(GPUScene);
    HZ_NON_MOVABLE(GPUScene);

    // =========================================================================
    // Mesh Registration (call at load time)
    // =========================================================================

    /**
     * @brief Register a mesh and upload its geometry to the mega-buffer
     * @param mesh The mesh to register
     * @return Mesh index for use in add_object()
     */
    [[nodiscard]] u32 register_mesh(const Mesh& mesh);

    /**
     * @brief Check if a mesh is already registered
     */
    [[nodiscard]] bool is_mesh_registered(const Mesh& mesh) const;

    /**
     * @brief Get mesh index for a registered mesh
     */
    [[nodiscard]] u32 get_mesh_index(const Mesh& mesh) const;

    // =========================================================================
    // Per-Frame Object Submission
    // =========================================================================

    /**
     * @brief Begin a new frame, reset object list
     */
    void begin_frame();

    /**
     * @brief Add an object to be rendered this frame
     * @param transform World transform matrix
     * @param mesh_index Index from register_mesh()
     * @param material_index Material index for bindless textures
     * @param bounding_sphere Bounding sphere in local space
     * @param flags Object flags
     * @return Object index
     */
    u32 add_object(const glm::mat4& transform, u32 mesh_index, u32 material_index,
                   const glm::vec4& bounding_sphere,
                   GPUObjectFlags flags = GPUObjectFlags::Visible);

    /**
     * @brief End frame, upload object data to GPU
     */
    void end_frame();

    // =========================================================================
    // Buffer Accessors (for compute shader and indirect draw)
    // =========================================================================

    [[nodiscard]] rhi::Buffer* object_buffer() const { return m_object_buffer.get(); }
    [[nodiscard]] rhi::Buffer* mesh_info_buffer() const { return m_mesh_info_buffer.get(); }
    [[nodiscard]] rhi::Buffer* draw_command_buffer() const { return m_draw_command_buffer.get(); }
    [[nodiscard]] rhi::Buffer* draw_count_buffer() const { return m_draw_count_buffer.get(); }

    [[nodiscard]] rhi::Buffer* vertex_buffer() const { return m_vertex_mega_buffer.get(); }
    [[nodiscard]] rhi::Buffer* index_buffer() const { return m_index_mega_buffer.get(); }

    [[nodiscard]] u32 object_count() const { return static_cast<u32>(m_objects.size()); }
    [[nodiscard]] u32 mesh_count() const { return static_cast<u32>(m_mesh_infos.size()); }

    [[nodiscard]] const GPUSceneConfig& config() const { return m_config; }

private:
    void create_buffers();
    void upload_mesh_data(const Mesh& mesh, u32 mesh_index);

    rhi::Device& m_device;
    GPUSceneConfig m_config;

    // Per-frame object data (CPU staging)
    std::vector<GPUObjectData> m_objects;

    // Static mesh info (uploaded once per mesh)
    std::vector<GPUMeshInfo> m_mesh_infos;

    // GPU Buffers
    std::unique_ptr<rhi::Buffer> m_object_buffer;       // SSBO: GPUObjectData[]
    std::unique_ptr<rhi::Buffer> m_mesh_info_buffer;    // SSBO: GPUMeshInfo[]
    std::unique_ptr<rhi::Buffer> m_draw_command_buffer; // Indirect: GPUDrawCommand[]
    std::unique_ptr<rhi::Buffer> m_draw_count_buffer;   // Indirect count: u32

    // Mega-buffers for all mesh geometry
    std::unique_ptr<rhi::Buffer> m_vertex_mega_buffer;
    std::unique_ptr<rhi::Buffer> m_index_mega_buffer;

    // Current offsets into mega-buffers
    u32 m_vertex_offset{0};
    u32 m_index_offset{0};

    // Mesh pointer to index mapping (for deduplication)
    std::unordered_map<const Mesh*, u32> m_mesh_index_map;
};

} // namespace hz
